*This statement will allow us to access NumPy objects using np.X instead of numpy.X.*

In [268]:
import numpy as np

# ***Array Basics***

**An array can be created from a list**

In [269]:
a = np.array([1, 4, 5, 8], float)
a

array([1., 4., 5., 8.])

In [270]:
type(a)

numpy.ndarray

**Array elements are accessed, sliced, and manipulated just like lists:**

In [271]:
a[:2]

array([1., 4.])

In [272]:
a[3]

8.0

In [273]:
a[0] = 5

In [274]:
a

array([5., 4., 5., 8.])

**Arrays can be multidimensional. Unlike lists, different axes are accessed using commas inside bracket notation**

In [275]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [276]:
a[0,0]

1.0

In [277]:
a[0,1]

2.0

**Array Slicing works with multiple dimensions**

In [278]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
a[1,:]

array([4., 5., 6.])

In [279]:
a[:,2]

array([3., 6.])

In [280]:
a[-1:,-2:]

array([[5., 6.]])

**The shape property of an array returns a tuple with the size of each array dimension, and the dtype property tells you what type of values are stored by the array**

In [281]:
a.shape

(2, 3)

In [282]:
a.dtype

dtype('float64')

**The len function returns the length of the first axis, and the in statement can be used to test if values are present in an array**

In [283]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
len(a)

2

In [284]:
2 in a

True

In [285]:
0 in a

False

**Arrays can be reshaped using tuples that specify new dimensions**

In [286]:
a = np.array(range(10), float)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [287]:
a = a.reshape((5,2))
a

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [288]:
a.shape

(5, 2)

*Notice that the reshape function creates a new array and does not itself modify the original array.*

**Keep in mind that Python's name-binding approach still applies to arrays. The copy function can be used to create a new, separate copy of an array in memory if needed:**

In [289]:
a = np.array([1, 2, 3], float)
b = a
c = a.copy()
a[0] = 0

In [290]:
a

array([0., 2., 3.])

In [291]:
b

array([0., 2., 3.])

In [292]:
c

array([1., 2., 3.])

**One can fill an array with a single value**

In [293]:
a = np.array([1, 2, 3], float)
a

array([1., 2., 3.])

In [294]:
a.fill(0)
a

array([0., 0., 0.])

**Two or more arrays can be concatenated together using the concatenate function with a tuple of the arrays to be joined.**

In [295]:
a = np.array([1,2], float)
b = np.array([3, 4, 5, 6], float)
b = np.array([7, 8, 9], float)
np.concatenate((a, b, c))

array([1., 2., 7., 8., 9., 1., 2., 3.])

In [296]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7, 8]], float)
np.concatenate ((a, b))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [297]:
np.concatenate((a,b), axis=0)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [298]:
np.concatenate((a,b), axis=1)

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

**The dimensionality of an array can be increased using the newaxis constant in bracket notation:**

In [299]:
a = np.array([1, 2, 3], float)
a

array([1., 2., 3.])

In [300]:
a[:,np.newaxis]

array([[1.],
       [2.],
       [3.]])

In [301]:
a[:,np.newaxis].shape

(3, 1)

In [302]:
b[np.newaxis,:]

array([[[5., 6.],
        [7., 8.]]])

In [303]:
b[np.newaxis,:].shape

(1, 2, 2)

*The newaxis approach is convenient for generating the proper dimensioned arrays for vector and matrix mathematics.*

# ***Array Mathematics***

**For two-dimensional arrays, multiplication remains elementwise and does not correspond to matrix multiplication.**

In [304]:
a = np.array([[1,2], [3,4]], float)
b = np.array([[2,0], [1,3]], float)
a * b

array([[ 2.,  0.],
       [ 3., 12.]])

**For arrays that do not match in the number of dimensions, Python will broadcast them to perform mathematical operations.**

In [305]:
a = np.array([[1,2], [3,4], [5,6]], float)
b = np.array([-1,3], float)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [306]:
b

array([-1.,  3.])

In [307]:
a + b

array([[0., 5.],
       [2., 7.],
       [4., 9.]])

**In addition to the standard operators, NumPy offers a large library of common mathematical functions that can be applied elementwise to arrays**

*abs, sign, sqrt, log, log10, exp, sin, cos, tan, arcsin, arccos, arctan, sinh, cosh, tanh, arcsinh, arccosh, arctanh, floor, ceil, rint, pi, e*

**Iterate over arrays**

In [308]:
a = np.array([1, 4, 5], int)
for x in a:
  print (x)

1
4
5


In [309]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for x in a:
  print(x)

[1. 2.]
[3. 4.]
[5. 6.]


In [310]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for (x, y) in a:
  print (x * y)

2.0
12.0
30.0


# ***Basic Array Operations***

**Many functions exist for extracting whole-array properties**
*   Member functions of the arrays such as *.sum()* or *.prod()*
*   Standalone functions in the NumPy module such as *np.sum()* or *np.prod()*


**A number of routines enable computation of statistical quantities in array datasets**

*.mean(), .var(), .std(), .min(), .max(), .argmin(), .argmax()*


***For multidimensional arrays, each of the functions thus far described can take an optional argument axis that will perform an operation along only the specified axis***

In [311]:
a = np.array ([[0, 2], [3, -1], [3, 5]], float)
a.mean(axis=0)

array([2., 2.])

In [312]:
a.mean(axis=1)

array([1., 1., 4.])

In [313]:
a.max(axis=0)

array([3., 5.])

**Like lists, arrays can be sorted and clipped**

In [314]:
a = np.array([6, 2, 5, -1, 0], float)
sorted(a)

[-1.0, 0.0, 2.0, 5.0, 6.0]

In [315]:
a.sort()
a

array([-1.,  0.,  2.,  5.,  6.])

In [316]:
a = np.array([6, 2, 5, -1, 0], float)
a.clip(0, 5)

array([5., 2., 5., 0., 0.])

**Unique elements can be extracted from an array**

In [317]:
a = np.array([1, 1, 4, 5, 5, 5, 7], float)
np.unique(a)

array([1., 4., 5., 7.])

**For two dimensional arrays, the diagonal can be extracted**

In [318]:
a = np.array([[1, 2], [3, 4]], float)
a.diagonal()

array([1., 4.])

**Comparison Operators and Value Testing**

In [319]:
a = np.array([1, 3, 0], float)
b = np.array([0, 3, 2], float)
a > b

array([ True, False, False])

In [320]:
c = a > b
c

array([ True, False, False])

In [321]:
a = np.array ([1, 3, 0], float)
a > 2

array([False,  True, False])

In [322]:
c = np.array([True, False, False], bool)
any(c)

True

In [323]:
all(c)

False

In [324]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3)

array([ True, False, False])

In [325]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [326]:
c = np.array([False, True, False], bool)
np.logical_or(b, c)

array([ True,  True,  True])

In [327]:
a = np.array([[0, 1], [3,0]], float)
a.nonzero()

(array([0, 1]), array([1, 0]))

In [328]:
a = np.array([1, np.NaN, np.Inf], float)
a

array([ 1., nan, inf])

In [329]:
np.isnan(a)

array([False,  True, False])

In [330]:
np.isfinite(a)

array([ True, False, False])

**Array Item Selection and Manipulation**

*Boolean arrays can be used as array selectors*

In [331]:
a = np.array([[6, 4], [5, 9 ]], float)
a >= 6

array([[ True, False],
       [False,  True]])

In [332]:
a[a >= 6]

array([6., 9.])

*Inaddition to Boolean selection, it is possible to select using integer arrays*

In [333]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a[b]

array([2., 2., 4., 8., 6., 4.])

*Lists can also be used as selection arrays*

In [334]:
a = np.array([2, 4, 6, 8], float)
a [[0, 0, 1, 3, 2, 1]]

array([2., 2., 4., 8., 6., 4.])

**Vector and matrix Mathematics**

In [335]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([2, 3], float)
c = np.array([[1, 1], [4, 0]], float)
a

array([[0., 1.],
       [2., 3.]])

In [336]:
np.dot(b, a)

array([ 6., 11.])

In [337]:
np.dot(a, b)

array([ 3., 13.])

In [338]:
np.dot(a, c)

array([[ 4.,  0.],
       [14.,  2.]])

In [339]:
np.dot(c, a)

array([[2., 4.],
       [0., 4.]])

In [340]:
a = np.array([[4, 2, 0], [9, 3, 7], [1, 2, 1]], float)
a

array([[4., 2., 0.],
       [9., 3., 7.],
       [1., 2., 1.]])

In [341]:
np.linalg.det(a)

-48.00000000000003

***One can find the eigenvalues and eigenvectors of a matrix***

In [342]:
vals, vecs = np.linalg.eig(a)
vals

array([ 8.85591316,  1.9391628 , -2.79507597])

In [343]:
vecs

array([[-0.3663565 , -0.54736745,  0.25928158],
       [-0.88949768,  0.5640176 , -0.88091903],
       [-0.27308752,  0.61828231,  0.39592263]])

***The inverse of a matrix can be found***

In [344]:
b = np.linalg.inv(a)
b

array([[ 0.22916667,  0.04166667, -0.29166667],
       [ 0.04166667, -0.08333333,  0.58333333],
       [-0.3125    ,  0.125     ,  0.125     ]])

In [345]:
np.dot(a, b)

array([[1.00000000e+00, 5.55111512e-17, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 2.22044605e-16],
       [0.00000000e+00, 1.38777878e-17, 1.00000000e+00]])

***It is also possible to generate the inner, outer and cross products of matrices and vectors.***

For vectors note that the inner product is equivalent to the dot product:

In [346]:
a = np.array([1, 4, 0], float)
b = np.array([2, 2, 1], float)
np.outer(a, b)

array([[2., 2., 1.],
       [8., 8., 4.],
       [0., 0., 0.]])

In [347]:
np.inner(a, b)

10.0

In [348]:
np.cross(a, b)

array([ 4., -1., -6.])

***The median can be found:***

In [349]:
a = np.array([1, 4, 3, 8, 9, 2, 3], float)
np.median(a)

3.0

***Correlation coefficient and covariance for multiple variables observed at multiple instances can be found:***

In [350]:
a = np.array([[1, 2, 1, 3], [5, 3, 1, 8]], float)
c = np.corrcoef(a)
c

array([[1.        , 0.72870505],
       [0.72870505, 1.        ]])

In [351]:
np.cov(a)

array([[0.91666667, 2.08333333],
       [2.08333333, 8.91666667]])

**Random Numbers: using the sub-module random**

***An array of random numbers in the half open interval [0.0, 1.0] can be generated***

In [352]:
np.random.rand(5)

array([0.05628964, 0.76388621, 0.040438  , 0.63322282, 0.56335605])

***The rand function can be used to generate two dimenesional random arrays, or the resize function could be employed here:***

In [353]:
np.random.rand(2,3)

array([[0.79088572, 0.78260548, 0.87265279],
       [0.3033978 , 0.52480211, 0.84582619]])

In [354]:
np.random.rand(6) .reshape((2,3))

array([[0.23616659, 0.52532549, 0.54730126],
       [0.77270141, 0.02613753, 0.43362064]])

***To generate a single random number in [0.0, 1.0]***

In [355]:
np.random.random()

0.9123264392740805

***To gnerate random integers in the range[min, max] use randint (min, max)***

In [356]:
np.random.randint(5, 10)

8